{
  "openapi": "3.0.0",
  "info": {
    "title": "Todo API",
    "description": "Manage tasks made for projects or independent tasks for user have a control of what he needs to do",
    "version": "1.0.0",
    "contact": {
      "name": "Matheus Dantas Ricardo",
      "url": "https://github.com/matheus-dr",
      "email": "matheus-dr@proton.me"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/v1/todo",
      "description": "Local environment"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Makes the login into our application",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                },
                "example": {
                  "email": "123@email.com",
                  "password": "Strong password"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "Success",
                    "token": "Bearer ..."
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/auth/recover-password": {},
    "/auth/change-forgotten-password": {},
    "/user": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Creates an user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "phone": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  },
                  "passwordVerification": {
                    "type": "string",
                    "required": true
                  }
                },
                "example": {
                  "username": "string",
                  "email": "string",
                  "phone": "string",
                  "password": "string",
                  "passwordVerification": "string"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Find all users",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "image": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "string",
                    "username": "string",
                    "email": "string",
                    "image": "string"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Find one user by id",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id"
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "image": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "uuid",
                    "username": "string",
                    "phone": "string",
                    "email": "string",
                    "image": "string"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Updates an user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "required": false
                  }
                },
                "example": {
                  "username": "string"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Deletes an user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/category": {},
    "/category/{id}": {},
    "/criticality-level": {},
    "/criticality-level/{id}": {},
    "/task": {},
    "/task/{id}": {},
    "/project": {},
    "/project/{id}": {}
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}